# Generated by Django 2.1.4 on 2019-06-22 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('indirizzo', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cellulare', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Rubrica',
                'verbose_name_plural': 'Rubrica',
            },
        ),
        migrations.CreateModel(
            name='Rubricar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('incarico', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cellulare', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('ragione_sociale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomi.Rubrica')),
            ],
            options={
                'verbose_name': 'Nomi in Rubrica',
                'verbose_name_plural': 'Nomi in Rubrica',
            },
        ),
    ]
